
  - name: ping the server
    hosts: web #which hosts your ansible wants to connect
    tasks: #list of tasks/modules/collections
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:

      - name: Induce an exception to see what happens
        ansible.builtin.ping:
        data: crash