- name: install nginx and run
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: install ingix service
    ansible.builtin.service:
      name: nginx service
      state: installed
      enable: yes  
  