- name: variable to print
  hosts: web
  tasks: 
  vars: 
    course: "DevOps"
    duration: "4 Months"
    trainer: "Siva Kumar Reddy"

  - name: print the information
    ansible.builtin.debug: # This is a module
      msg: "Im learning {{course}}, with {{duration}}, aws from {{tainer}}" 
