- name: vars prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Enter your course name
    private: false # Not confindential
  - name: DURATION
    prompt: Enter your duration
  - name: TRAINER
    prompt: Enter trainer name
    private: false # not confidential
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "I am learing {{COURSE}}, with {{DURATION}}, my {{TRAINER}}"
