- name: install naginx
  hosts: web
  become: yes

  tasks: 
  - name: installing nginx
    yum: 
     name: nginx
     state: present
  - name: service
    service: 

     name: nginx
     state: present 
     state: started
      
